# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.api_commerce: 'http://127.0.0.1:8000/soap?wsdl'
    app.bouchonne: 'on'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $bouchonne: '%app.bouchonne%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    ressource:
        class: App\Service\Ressource
        arguments:
            $bouchonne: '%app.bouchonne%' 


    # ajouter le service de CountryAPI
    commerce.produit:
        class: App\Service\CommerceAPI
        arguments:
            $api_commerce: '%app.api_commerce%' 
            $ressource: '@App\Service\ProduitService'
        
    commerce.categorie:
        class: App\Service\CommerceAPI
        arguments:
            $api_commerce: '%app.api_commerce%' 
            $ressource: '@App\Service\CategorieService'        

    App\Service\CommerceAPI: '@commerce.produit'
    App\Service\CommerceAPI $c: '@commerce.categorie'      

    all_data.commerceproduit:
        class: App\Service\AllData
        arguments:
            $service: '@commerce.produit'
            
    all_data.commercecategorie:
        class: App\Service\AllData
        arguments:
            - '@commerce.categorie'
    
    App\Service\AllData $commerceProduit: '@all_data.commerceproduit'
    App\Service\AllData $commerceCategorie: '@all_data.commercecategorie'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
